# -----------------------------------------------------------------------------
# MLflow backend store: Aurora Serverless v2 PostgreSQL that scales to zero.
# Pauses after var.db_auto_pause_seconds idle (storage-only cost), wakes in
# ~15s on the next connection. Password generated by RDS and kept in Secrets
# Manager - never in code or Terraform state.
# -----------------------------------------------------------------------------
resource "aws_db_subnet_group" "mlflow" {
  name        = "${var.project_name}-mlflow"
  description = "Private subnets for the MLflow database"
  subnet_ids  = local.private_subnet_ids
}

resource "aws_security_group" "db" {
  #checkov:skip=CKV2_AWS_5:Attached to the Aurora cluster below
  name        = "${var.project_name}-mlflow-db"
  description = "MLflow Aurora PostgreSQL - Postgres from inside the VPC only"
  vpc_id      = local.vpc_id

  tags = {
    Name = "${var.project_name}-mlflow-db"
  }
}

# EKS pods get real VPC IPs, so allowing the VPC CIDR covers MLflow wherever it runs
resource "aws_vpc_security_group_ingress_rule" "db_from_vpc" {
  security_group_id = aws_security_group.db.id
  description       = "PostgreSQL from within the VPC"
  cidr_ipv4         = local.vpc_cidr_block
  ip_protocol       = "tcp"
  from_port         = 5432
  to_port           = 5432
}

resource "aws_rds_cluster" "mlflow" {
  #checkov:skip=CKV_AWS_327:AWS-managed encryption key is sufficient; avoids KMS cost
  #checkov:skip=CKV_AWS_162:IAM DB auth not supported by MLflow's SQLAlchemy connection
  #checkov:skip=CKV2_AWS_8:Covered by automated backups (7 days)
  cluster_identifier = "${var.project_name}-mlflow"
  engine             = "aurora-postgresql"
  engine_mode        = "provisioned" # Serverless v2 uses provisioned mode + db.serverless instances
  engine_version     = var.aurora_engine_version

  database_name               = "mlflow"
  master_username             = "mlflow_admin"
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.mlflow.name
  vpc_security_group_ids = [aws_security_group.db.id]
  storage_encrypted      = true

  backup_retention_period = 7
  preferred_backup_window = "03:00-04:00"
  copy_tags_to_snapshot   = true

  # It holds real data - make deleting it a deliberate, multi-step act
  deletion_protection       = true
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.project_name}-mlflow-final"

  apply_immediately = true

  serverlessv2_scaling_configuration {
    min_capacity             = 0 # scale to zero = auto-pause when idle
    max_capacity             = var.db_max_acu
    seconds_until_auto_pause = var.db_auto_pause_seconds
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_rds_cluster_instance" "mlflow" {
  #checkov:skip=CKV_AWS_118:Enhanced monitoring not needed for this workload
  #checkov:skip=CKV_AWS_353:Performance Insights not needed for this workload
  identifier         = "${var.project_name}-mlflow-1"
  cluster_identifier = aws_rds_cluster.mlflow.id
  instance_class     = "db.serverless"
  engine             = aws_rds_cluster.mlflow.engine
  engine_version     = aws_rds_cluster.mlflow.engine_version

  # Version changes go through a PR, not silently overnight
  auto_minor_version_upgrade = false
  publicly_accessible        = false
}
